baseurl: "https://duong.page"
contentdir: content
layoutdir: layouts
publishdir: public
title: Duong
canonifyurls: true

DefaultContentLanguage: en
theme: beautifulhugo
metaDataFormat: yaml
pygmentsUseClasses: true
pygmentCodeFences: true

Params:
  subtitle: Duong's Blog
  logo: img/duong.jpg
  favicon: img/duong.ico
  dateFormat: "January 2, 2006"
  commit: false
  rss: true
  comments: true
  author:
    name: Duong Nguyen
    email: duongnv129@gmail.com
    github: duongnv129
    twitter: duongnv129
    linkedin: duongnv129

menu:
  main:
    - name: Blog
      url: tags/me
      weight: 1
    - name: Technology
      url: tags/tech
      weight: 2
    - name: About
      url: page/about/
      weight: 3
    - name: Tags
      url: tags
      weight: 3
